### ISSUE TITLE
IdentityMap#load returns an Array sometimes and a Set other times

### ISSUE THREAD

**Issue by justingaylor** [rightscale/praxis-mapper#2]
For reasons unknown, `IdentityMap#load` is returning an `Array` for two of my three calls and a `Set` for the other call. Then, when attempting to join the results together with the `+` operator, I am getting a "no implicit conversion of Set into Array" error.

**Comment by careo** [comment]
This should be fixed long ago. `Identitymap#load` is always returning an array of records now.
