### ISSUE TITLE
Calling IdentityMap#all with a condition whose value is_a?(Integer) fails

### ISSUE THREAD

**Issue by justingaylor** [rightscale/praxis-mapper#3]
Calling IdentityMap#all with a condition whose value is an `Integer` fails with:

```
undefined method `each_with_object' for 292923003:Fixnum
```

The offending line of code is here, where it is assumed that the values are an `Enumerable` (which responds to size):

https://github.com/rightscale/praxis-mapper/blob/0d9558edffc4844b93853b192cc3f52ce7340eca/lib/praxis-mapper/identity_map.rb#L331

However, `Integer` also provides a `size` method, which returns the size of the Integer in bytes.

Do we not support this syntax for calling the IdentityMap#all method?

```
identity_map.all(MyModel, :association_id => 10)
```

**Comment by careo** [comment]
The conditions passed to `IdentityMap#all` must always be an array at the first level. Otherwise we can not differentiate between passing multiple values, or one value that is itself an array.
